Fix backprop dim for unused lstm states on gpu
I discovered this when I didn't use all the states of the rnn
encoding further down the pipeline. My code ran fine on cpu but I
got the following error when using gpu.

"python3.5/site-packages/chainer/functions/connection/n_step_rnn.py",
line 449, in backward
    dys = cuda.cupy.concatenate(dy_list, axis=0)

cupy.core.core.concatenate_method (cupy/core/core.cpp:64040)
ValueError: All arrays must have same shape except the axis to
concatenate

I think x_list[i] has correct 0th dimension (batch size) but
incorrect 1st dimension (num units). This change got my code
working - and I checked it both for a unidirectional and a
bidirectional rnn.